//! `#[forge_struct]` proc macro — generates CUDA struct definition for custom types.

use proc_macro2::TokenStream;
use quote::quote;
use syn::{parse2, DeriveInput, Fields, Type, TypePath};

use crate::cuda_emit::scalar_to_cuda_pub;

pub fn expand_forge_struct(input: TokenStream) -> Result<TokenStream, syn::Error> {
    let input: DeriveInput = parse2(input)?;
    let struct_name = &input.ident;
    let struct_name_str = struct_name.to_string();

    // Only works on structs with named fields
    let fields = match &input.data {
        syn::Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    struct_name,
                    "#[forge_struct] requires named fields",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                struct_name,
                "#[forge_struct] only works on structs",
            ));
        }
    };

    // Generate CUDA struct definition
    let mut cuda_fields = Vec::new();
    for field in fields.iter() {
        let field_name = field.ident.as_ref().unwrap().to_string();
        let rust_type = type_to_string(&field.ty);
        let cuda_type = scalar_to_cuda_pub(&rust_type).map_err(|_| {
            syn::Error::new_spanned(
                &field.ty,
                format!("unsupported field type '{}' in #[forge_struct]", rust_type),
            )
        })?;
        cuda_fields.push(format!("    {} {};", cuda_type, field_name));
    }

    let cuda_struct = format!(
        "struct {} {{\n{}\n}};\n",
        struct_name_str,
        cuda_fields.join("\n")
    );

    // Generate operator overloads for arithmetic if all fields are same type
    let field_types: Vec<String> = fields.iter().map(|f| type_to_string(&f.ty)).collect();
    let field_names: Vec<String> = fields.iter().map(|f| f.ident.as_ref().unwrap().to_string()).collect();
    let all_same_type = field_types.iter().all(|t| t == &field_types[0]);

    let mut ops = String::new();
    if all_same_type && !field_names.is_empty() {
        let sn = &struct_name_str;

        // operator+
        let add_fields: String = field_names.iter().map(|f| format!("a.{f} + b.{f}")).collect::<Vec<_>>().join(", ");
        ops.push_str(&format!("__device__ {sn} operator+({sn} a, {sn} b) {{ return {sn}{{{add_fields}}}; }}\n"));

        // operator-
        let sub_fields: String = field_names.iter().map(|f| format!("a.{f} - b.{f}")).collect::<Vec<_>>().join(", ");
        ops.push_str(&format!("__device__ {sn} operator-({sn} a, {sn} b) {{ return {sn}{{{sub_fields}}}; }}\n"));

        // operator* (scalar)
        let cuda_scalar = scalar_to_cuda_pub(&field_types[0]).unwrap_or("float");
        let mul_fields: String = field_names.iter().map(|f| format!("a.{f} * b")).collect::<Vec<_>>().join(", ");
        ops.push_str(&format!("__device__ {sn} operator*({sn} a, {cuda_scalar} b) {{ return {sn}{{{mul_fields}}}; }}\n"));
        let mul_fields2: String = field_names.iter().map(|f| format!("a * b.{f}")).collect::<Vec<_>>().join(", ");
        ops.push_str(&format!("__device__ {sn} operator*({cuda_scalar} a, {sn} b) {{ return {sn}{{{mul_fields2}}}; }}\n"));
    }

    let full_cuda = format!("{}{}", cuda_struct, ops);

    let mod_name = quote::format_ident!("{}_forge_meta", struct_name);

    Ok(quote! {
        #input

        #[doc(hidden)]
        pub mod #mod_name {
            /// CUDA struct definition generated by #[forge_struct].
            pub const CUDA_STRUCT_DEF: &str = #full_cuda;
            /// Struct name for kernel codegen.
            pub const STRUCT_NAME: &str = #struct_name_str;
        }
    })
}

fn type_to_string(ty: &Type) -> String {
    match ty {
        Type::Path(TypePath { path, .. }) => {
            path.segments.iter().map(|s| s.ident.to_string()).collect::<Vec<_>>().join("::")
        }
        _ => "unknown".to_string(),
    }
}
